const PDFDocument = require('pdfkit');

/**
 * Compile AI summary text and database rows into an enterprise PDF document
 * @param {string} summaryText Narrative summary generated by LLM Prompt B
 * @param {array} rows Dataset rows
 * @returns {Promise<Buffer>} PDF file bytes buffer
 */
function generateAnalyticsReportPdf(summaryText, rows) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: 'A4', margin: 40 });
            const buffers = [];

            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                resolve(Buffer.concat(buffers));
            });

            // ---------------- PAGE 1: TITLE & EXECUTIVE SUMMARY ----------------
            // Title Header Banner
            doc.rect(40, 40, 515, 60).fill('#1e3a8a');
            doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(20).text('AI BUSINESS INTELLIGENCE REPORT', 55, 60);
            doc.fillColor('#93c5fd').font('Helvetica').fontSize(10).text('Analytics Engine Intelligence Summary', 55, 82);

            doc.y = 120; // reset cursor after banner

            // Generation Date
            doc.fillColor('#6b7280').font('Helvetica').fontSize(8).text(`Generated on: ${new Date().toLocaleString()}`, { align: 'right' });
            doc.moveDown(1.5);

            // Executive Summary Title
            doc.fillColor('#1f2937').font('Helvetica-Bold').fontSize(14).text('Executive Summary Analysis');
            doc.moveDown(0.8);

            // Print AI Summary Text
            // Clean up alert block headers if they exist in markdown (e.g. > [!NOTE])
            const cleanSummary = summaryText
                .replace(/>\s*\[!(NOTE|IMPORTANT|WARNING|TIP|CAUTION)\]/g, '')
                .replace(/>/g, '')
                .trim();

            doc.fillColor('#374151').font('Helvetica').fontSize(10.5).text(cleanSummary, { align: 'justify', lineGap: 3 });
            doc.moveDown(2);

            // ---------------- PAGE 2+: DATA RECORDS TABLE ----------------
            doc.addPage();

            // Table Title
            doc.fillColor('#1e3a8a').font('Helvetica-Bold').fontSize(14).text('Complete Dataset Records');
            doc.moveDown(0.8);

            if (rows && rows.length > 0) {
                const keys = Object.keys(rows[0]);
                const displayKeys = keys.slice(0, 6); // Limit to max 6 columns to fit A4 layout width
                
                let currentY = doc.y;
                const tableWidth = 515;
                const colWidth = tableWidth / displayKeys.length;

                // Draw Table Header
                doc.rect(40, currentY, tableWidth, 20).fill('#1e3a8a');
                doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8.5);

                for (let i = 0; i < displayKeys.length; i++) {
                    // Title casing columns
                    const headerName = String(displayKeys[i])
                        .replace(/_/g, ' ')
                        .replace(/\b\w/g, c => c.toUpperCase());
                    doc.text(headerName, 45 + (i * colWidth), currentY + 6, { width: colWidth - 8, ellipsis: true });
                }

                currentY += 20;
                doc.fillColor('#374151').font('Helvetica').fontSize(8.5);

                // Print rows
                let index = 0;
                for (const row of rows) {
                    // Check if we need to insert a page break
                    if (currentY > 760) {
                        doc.addPage();
                        currentY = 40;

                        // Redraw Table Header
                        doc.rect(40, currentY, tableWidth, 20).fill('#1e3a8a');
                        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8.5);

                        for (let i = 0; i < displayKeys.length; i++) {
                            const headerName = String(displayKeys[i])
                                .replace(/_/g, ' ')
                                .replace(/\b\w/g, c => c.toUpperCase());
                            doc.text(headerName, 45 + (i * colWidth), currentY + 6, { width: colWidth - 8, ellipsis: true });
                        }

                        currentY += 20;
                        doc.fillColor('#374151').font('Helvetica').fontSize(8.5);
                    }

                    // Alternating backgrounds
                    if (index % 2 === 1) {
                        doc.rect(40, currentY, tableWidth, 18).fill('#f3f4f6');
                        doc.fillColor('#374151');
                    }

                    for (let i = 0; i < displayKeys.length; i++) {
                        const val = row[displayKeys[i]];
                        const displayVal = val instanceof Date 
                            ? val.toLocaleDateString() 
                            : (val != null ? String(val) : '');
                        doc.text(displayVal, 45 + (i * colWidth), currentY + 5, { width: colWidth - 8, ellipsis: true });
                    }

                    currentY += 18;
                    index++;
                }

                // If rows exceed display limits, notify at end of PDF
                if (keys.length > 6) {
                    doc.moveDown(1);
                    doc.fillColor('#6b7280').font('Helvetica-Oblique').fontSize(8).text(`* Note: Table displays the first 6 columns of the dataset. Full columns are exported inside the CSV format file.`, 40, currentY + 10);
                }

            } else {
                doc.text('No matching data records found.');
            }

            // Global Footer page numbering retrospectively
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.fillColor('#9ca3af').fontSize(8).text(`Page ${i + 1} of ${pages.count}`, 40, doc.page.height - 40, { align: 'center', width: 515 });
            }

            doc.end();
        } catch (e) {
            reject(e);
        }
    });
}

module.exports = {
    generateAnalyticsReportPdf
};
